
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copilot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copilot-backend
  template:
    metadata:
      labels:
        app: copilot-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/your-project/copilot-backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: copilot-backend
spec:
  type: LoadBalancer
  selector:
    app: copilot-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
