
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copilot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copilot-frontend
  template:
    metadata:
      labels:
        app: copilot-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/your-project/copilot-frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: "http://copilot-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: copilot-frontend
spec:
  type: LoadBalancer
  selector:
    app: copilot-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
