
apiVersion: v1
kind: Service
metadata:
  name: copilot-frontend
spec:
  selector:
    app: copilot-frontend
  ports:
  - port: 80
    targetPort: {{ .Values.service.frontend.port }}
  type: ClusterIP
