
name: Deploy Copilot to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: your-project
  CLUSTER_NAME: your-cluster
  CLUSTER_ZONE: us-east1-c
  REGION: us
  REPO_NAME: cicd-repo
  BACKEND_IMAGE: us-docker.pkg.dev/your-project/cicd-repo/copilot-backend:latest
  FRONTEND_IMAGE: us-docker.pkg.dev/your-project/cicd-repo/copilot-frontend:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        token_format: "access_token"
        decode_json: true

    - name: Configure Docker
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: Build and Push Backend
      run: |
        docker build -f Dockerfile.backend -t $BACKEND_IMAGE .
        docker push $BACKEND_IMAGE

    - name: Build and Push Frontend
      run: |
        docker build -f Dockerfile.frontend -t $FRONTEND_IMAGE .
        docker push $FRONTEND_IMAGE
    
    - name: Initialize Terraform
      working-directory: terraform
      run: terraform init

    # - name: Terraform Format Check
    #   working-directory: terraform
    #   run: terraform fmt -check

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    # - name: Get GKE Credentials
    #   run: gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

    # - name: Deploy via Helm
    #   run: |
    #     helm upgrade --install copilot charts/copilot \
    #       --set image.backend.repository=us-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/copilot-backend \
    #       --set image.frontend.repository=us-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/copilot-frontend

    # - name: Apply IAP and Ingress Configs
    #   run: |
    #     kubectl apply -f iap-https-lb/
