
name: Deploy Copilot to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: your-project
  CLUSTER_NAME: your-cluster
  CLUSTER_ZONE: us-central1-c
  BACKEND_IMAGE: gcr.io/your-project/copilot-backend:latest
  FRONTEND_IMAGE: gcr.io/your-project/copilot-frontend:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Backend
      run: |
        docker build -f Dockerfile.backend -t $BACKEND_IMAGE .
        docker push $BACKEND_IMAGE

    - name: Build and Push Frontend
      run: |
        docker build -f Dockerfile.frontend -t $FRONTEND_IMAGE .
        docker push $FRONTEND_IMAGE

    - name: Get GKE Credentials
      run: gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/
        kubectl apply -f iap-https-lb/
